# Generated by Django 5.1.3 on 2024-11-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0002_keyword_created_at_keyword_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
