# Generated by Django 5.1.3 on 2024-11-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0004_product_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Mobiles, Computers', 'Mobiles, Computers'), ('TV, Appliances, Electronics', 'TV, Appliances, Electronics'), ("Men's Fashion", "Men's Fashion"), ("Women's Fashion", "Women's Fashion"), ('Home, Kitchen, Pets', 'Home, Kitchen, Pets'), ('Beauty, Health, Grocery', 'Beauty, Health, Grocery'), ('Sports, Fitness, Bags, Luggage', 'Sports, Fitness, Bags, Luggage'), ("Toys, Baby Products, Kids' Fashion", "Toys, Baby Products, Kids' Fashion"), ('Car, Motorbike, Industrial', 'Car, Motorbike, Industrial'), ('Books', 'Books'), ('Movies, Music & Video Games', 'Movies, Music & Video Games')], max_length=255)),
                ('search_volume', models.IntegerField()),
                ('competition', models.DecimalField(decimal_places=2, max_digits=5)),
                ('suggested_bid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
