# Generated by Django 5.1.3 on 2024-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0005_keywordanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordanalysis',
            name='avg_monthly_sales',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
