# Generated by Django 5.1.3 on 2024-12-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0007_alter_keywordanalysis_avg_monthly_sales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeywordAnalysis',
            new_name='KeywordForge',
        ),
    ]
