# Generated by Django 5.1.3 on 2024-12-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_tool', '0008_rename_keywordanalysis_keywordforge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeywordForge',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='name',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.CharField(choices=[('Mobiles, Computers', 'Mobiles, Computers'), ('TV, Appliances, Electronics', 'TV, Appliances, Electronics'), ("Men's Fashion", "Men's Fashion"), ("Women's Fashion", "Women's Fashion"), ('Home, Kitchen, Pets', 'Home, Kitchen, Pets'), ('Beauty, Health, Grocery', 'Beauty, Health, Grocery'), ('Sports, Fitness, Bags, Luggage', 'Sports, Fitness, Bags, Luggage'), ("Toys, Baby Products, Kids' Fashion", "Toys, Baby Products, Kids' Fashion"), ('Car, Motorbike, Industrial', 'Car, Motorbike, Industrial'), ('Books', 'Books'), ('Movies, Music & Video Games', 'Movies, Music & Video Games')], default='Uncategorized', max_length=255),
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(default='default_keyword', max_length=255),
        ),
        migrations.AddField(
            model_name='keyword',
            name='match_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyword',
            name='sponsored_asin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='suggested_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='search_volume',
            field=models.IntegerField(default=0),
        ),
    ]
